vrf instance TENANT-A
   rd 10.0.0.4:1

vlan 20
   name TENANT-A-L3

ip virtual-router mac-address 00:1c:73:00:00:01   ! Same virtual MAC as LEAF-1

interface Vlan10
   vrf TENANT-A
   ip address virtual 10.10.10.254/24             ! Same anycast IP as LEAF-1

interface Vlan20
   vrf TENANT-A
   ip address virtual 10.10.20.254/24

interface Vxlan1
   vxlan vlan 20 vni 10020
   vxlan vrf TENANT-A vni 99999
   vxlan flood vtep add 10.0.0.3

ip routing vrf TENANT-A

router bgp 65002
   vlan 20
      rd 10.0.0.4:10020
      route-target both 65001:10020          ! Match LEAF-1
      redistribute learned

   vrf TENANT-A
      rd 10.0.0.4:1
      route-target import evpn 65001:99999
      route-target export evpn 65001:99999
      redistribute connected
