interface Loopback0
   ip address 10.0.0.4/32

! Link to SPINE-1
interface Ethernet1
   description to-SPINE-1
   no switchport
   ip address 10.1.1.3/31
   no shutdown

! Link to SPINE-2
interface Ethernet2
   description to-SPINE-2
   no switchport
   ip address 10.1.2.3/31
   no shutdown

router bgp 65002
   router-id 10.0.0.4
   maximum-paths 2
   neighbor 10.1.1.2 remote-as 65000
   neighbor 10.1.1.2 description SPINE-1
   neighbor 10.1.1.2 send-community extended
   neighbor 10.1.1.2 maximum-routes 12000
   neighbor 10.1.2.2 remote-as 65000
   neighbor 10.1.2.2 description SPINE-2
   neighbor 10.1.2.2 send-community extended
   neighbor 10.1.2.2 maximum-routes 12000
   network 10.0.0.4/32

ip routing
