service routing protocols model multi-agent

interface Loopback0
   ip address 10.0.0.3/32

interface Management1
  ip address 192.168.100.13/24

! --- Fabric links to spines (point-to-point /31) ---
! Link to SPINE-1
interface Ethernet1
   description to-SPINE-1
   no switchport
   ip address 10.1.1.1/31
   no shutdown

! Link to SPINE-2
interface Ethernet2
   description to-SPINE-2
   no switchport
   ip address 10.1.2.1/31
   no shutdown

! --- eBGP underlay ---
router bgp 65001
   router-id 10.0.0.3
   maximum-paths 2               ! ECMP across both spines

   ! Neighbour toward SPINE-1
   neighbor 10.1.1.0 remote-as 65000
   neighbor 10.1.1.0 description SPINE-1
   neighbor 10.1.1.0 send-community extended
   neighbor 10.1.1.0 maximum-routes 12000

   ! Neighbour toward SPINE-2
   neighbor 10.1.2.0 remote-as 65000
   neighbor 10.1.2.0 description SPINE-2
   neighbor 10.1.2.0 send-community extended
   neighbor 10.1.2.0 maximum-routes 12000

   ! Advertise our loopback into the underlay
   network 10.0.0.3/32

! --- IP routing must be enabled on vEOS ---
ip routing
