vlan 10
   name TENANT-A-L2

interface Vxlan1
   vxlan source-interface Loopback0
   vxlan udp-port 4789
   vxlan vlan 10 vni 10010
   vxlan flood vtep 10.0.0.3                 ! BUM replication toward LEAF-1

router bgp 65002
   neighbor 10.1.1.2 route-map EVPN-OUT out
   neighbor 10.1.2.2 route-map EVPN-OUT out

   address-family evpn
      neighbor 10.1.1.2 activate
      neighbor 10.1.2.2 activate

   vlan 10
      rd 10.0.0.4:10010
      route-target both 65001:10010          ! Must match LEAF-1's route-target
      redistribute learned

route-map EVPN-OUT permit 10

! HOST-B on Ethernet3
interface Ethernet3
   description HOST-B
   switchport mode access
   switchport access vlan 10
   no shutdown
