router bgp 65000
   neighbor 10.1.1.1 route-map EVPN-OUT out
   neighbor 10.1.1.3 route-map EVPN-OUT out

   address-family evpn
      neighbor 10.1.1.1 activate
      neighbor 10.1.1.3 activate

route-map EVPN-OUT permit 10
